[[redirects]]
	from = "/ui-components/*"
	to = "/components/:splat"
	status = 300
	force = true

[[redirects]]
	from = "/style-guide/*"
	to = "/desigm-guidelines/:splat"
	status = 300
	force = true

[[redirects]]
	from = "/design-guidelines/status-system/"
	to = "/patterns/status-system"
	status = 300
	force = true
	
