backend:
    name: git-gateway
    branch: draft
media_folder: "/_content/img/uploads"
public_folder: "/img/public-imgs"
site_url: https://deploy-preview-98--astrouxds.netlify.app
display_url: https://deploy-preview-98--astrouxds.netlify.app
collections:
  - label: "Components"
    name: "components"
    folder: "/_content/components"
    create: true
    slug: "{{slug}}"
    preview_path: components/{{slug}}
    fields:
      - {label: "Page Title", name: "title", widget: "string", default: "Page Title"}
      - {label: "Page Class", name: "class", widget: "string", default: ""}
      - {label: "Date", name: "date", widget: "hidden", default: "Last Modified"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "components"}
      - {label: "Path", name: "path", widget: "hidden", default: "_content/components/{{slug}}"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "components.template.njk"}
      - {label: "Theme", name: 'theme', widget: "hidden", default: 'true'}
      - {label: "Demo Link", name: 'demo', widget: "string", default: "https://astro-components.netlify.app/iframe.html?id=components-slider--slider"}  
      - {label: "Demo Height", name: 'height', widget: "string", default: '200'}
      - {label: "Storybook Component Name", name: 'storybook', widget: "string", default: "components-slider--slider"}  
      - {label: "Git Link Name", name: 'git', widget: "string", default: "rux-component"}
      - {label: 'Page content', name: 'body', widget: 'markdown' }
  - label: "Design Guidelines"
    name: "design-guidelines"
    folder: "/_content/design-guidelines"
    create: true
    slug: "{{slug}}"
    preview_path: design-guidelines/{{slug}}
    fields:
      - {label: "Page Title", name: "title", widget: "string", default: "Page Title"}
      - {label: "Page Class", name: "class", widget: "string", default: ""}
      - {label: "Date", name: "date", widget: "hidden", default: "Last Modified"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "resources"}
      - {label: "Path", name: "path", widget: "hidden", default: "_content/design-guidelines/{{slug}}"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "interior.template.njk"}
      - label: "File Upload"
        name: "images"
        widget: "file"
        default: "/_content/img/design-guidelines"
        required: false
        media_library:
          config:
            multiple: true
      - {label: 'Page content', name: 'body', widget: 'markdown' }
  - label: "Design Process"
    name: "design-process"
    folder: "/_content/design-process"
    create: true
    slug: "{{slug}}"
    preview_path: design-process/{{slug}}
    fields:
      - {label: "Page Title", name: "title", widget: "string", default: "Page Title"}
      - {label: "Page Class", name: "class", widget: "string", default: ""}
      - {label: "Date", name: "date", widget: "hidden", default: "Last Modified"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "resources"}
      - {label: "Path", name: "path", widget: "hidden", default: "_content/design-process/{{slug}}"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "interior.template.njk"}
      - label: "File Upload"
        name: "images"
        widget: "file"
        default: "/_content/img/design-guidelines"
        media_library:
          config:
            multiple: true
      - {label: 'Page content', name: 'body', widget: 'markdown' }
  - label: "Patterns"
    name: "patterns"
    folder: "/_content/patterns"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Page Title", name: "title", widget: "string", default: "Page Title"}
      - {label: "Page Class", name: "class", widget: "string", default: ""}
      - {label: "Date", name: "date", widget: "hidden", default: "Last Modified"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "resources"}
      - {label: "Path", name: "path", widget: "hidden",default: "_content/patterns/{{slug}}"}
      - label: "Layout"
        name: "layout"
        widget: "select"
        options: ["interior.template.njk", "components.template.njk"]
      - {label: 'Page content', name: 'body', widget: 'markdown' }
  - label: "GRM Service UX Design"
    name: "grm-service-ux-design"
    folder: "/_content/grm-service-ux-design"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Page Title", name: "title", widget: "string", default: "Page Title"}
      - {label: "Page Class", name: "class", widget: "string", default: ""}
      - {label: "Date", name: "date", widget: "hidden", default: "Last Modified"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "resources"}
      - {label: "Path", name: "path", widget: "hidden",default: "_content/grm-service-ux-design/{{slug}}"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "interior.template.njk"}
      - {label: 'Page content', name: 'body', widget: 'markdown' }
      